name: school_management_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  logging: ^1.1.0
  flutter_facebook_auth: ^6.0.4
  shared_preferences: ^2.2.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth_web: ^5.0.0
  google_sign_in_ios: ^5.7.6
  js: ^0.6.3
  leak_tracker: 10.0.0
  leak_tracker_flutter_testing: 2.0.1
  leak_tracker_testing: 2.0.1
  material_color_utilities: 0.8.0
  meta: ^1.11.0
  test_api: 0.6.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  async: ^2.11.0
  intl: ^0.19.0
  uuid: ^4.4.0
  share_plus: ^9.0.0
  printing: ^5.12.0
  pdf: ^3.10.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
flutter:
  uses-material-design: true
  assets:
  - lib/assets/imagen/imagen01.jpg
  - lib/assets/imagen/logomain1.jpg
  - lib/assets/imagen/logomain2.png
  - lib/assets/imagen/googleicon.png
  - lib/assets/imagen/logoicon2.png